### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [hyperpress/pressmedics#87]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/hyperpress/pressmedics/blob/master/package.json#L50

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by hyperpress** [comment]
Thanks for the heads up. I've removed it in https://github.com/hyperpress/pressmedics/commit/f09f9e6ef247d586bab703f3a08af6b2e7396cc6
